In [1]:
import pandas as pd

In [2]:
pedalboards = pd.read_json('data/pedalboards.json')
pedalboards.columns = ['name', 0, 1, 2, 3, 4, 5]

pedalboards.head()

         name    0   1    2   3    4    5
0  AudioVerse  107  86   38  44  107  107
1  AudioChoru  107  27   75  38   69   53
2  AudioSolo*   27  75   71  69   53   85
3  Dark*Side*    1  73  105  54   78    3
4  Slash*****   28  68   23  73   99   59

In [3]:
plugins = pd.read_json('data/plugins.json')
plugins = plugins.sort_index()

plugins.head()

     category      name
0   Filter_EQ  M-Filter
1  Modulation   TheVibe
2         SFX   Z-Organ
3  Modulation    Slicer
4       Delay  PhaseDly

In [4]:
data = pd.DataFrame([], index=range(0, len(pedalboards)), columns=plugins.index)
data = data.fillna(0)

data.head()

,0,1,2,3,4,5,6,7,8,9,...,107,108,109,110,111,112,113,114,115,116
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
for index, pedalboard in pedalboards[[0, 1, 2, 3, 4, 5]].iterrows():
    for effect in pedalboard:
        data[effect][index] += 1

data.head()

,0,1,2,3,4,5,6,7,8,9,...,107,108,109,110,111,112,113,114,115,116
0,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# Save pedalboard
data.to_json('data/plugins-pedalboards.json')

## Visualizar plugins de Ã¡udio

For data show, replace index for pedalboard name

In [7]:
data.columns = plugins.name

data.head()

name,M-Filter,TheVibe,Z-Organ,Slicer,PhaseDly,FilterDly,PitchDly,StereoDly,BitCrush,Bomber,...,None,TONE CITY,B-BREAKER,BGN DRIVE,DELUXE-R,ALIEN,REVO-1,CAR DRIVE,MS 1959,VX JMI
0,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0